version: "3"

services:
  # transit 根据需要扩展 可部署多个
  transit:
    image: nancode/dora-transit:latest
    container_name: transit
    command: /cmd/transit -f /cmd/etc/config.yml
    ports:
      - "8221:8221"
    volumes:
      - ./etc:/cmd/etc
    networks:
      - default
      - dora_net

  # manage
  manage:
    image: nancode/dora-manage:latest
    container_name: manage
    command: /cmd/manage -f /cmd/etc/config.yml
    ports:
      - "8222:8222"
    volumes:
      - ./etc:/cmd/etc
    networks:
      - default
      - dora_net

  # webapp
  webapp:
    image: nancode/dora-webapp:latest
    container_name: webapp
    ports:
      - "8223:80"
    depends_on:
      - manage

networks:
  dora_net:
    external: true