version: "3"

services:
  # transit 根据需要扩展 可部署多个
  transit:
    image: registry.cn-hangzhou.aliyuncs.com/nancode/dora-transit:latest
    ports:
      - "8221:8221"
    volumes:
      - ./data:/app/tmp
      - ./config.yml:/app/config.yml

  # manage
  manage:
    image: registry.cn-hangzhou.aliyuncs.com/nancode/dora-manage:latest
    ports:
      - "8222:8222"
    volumes:
      - ./data:/app/tmp
      - ./config.yml:/app/config.yml

  # webapp
  webapp:
    image: registry.cn-hangzhou.aliyuncs.com/nancode/dora-webapp:latest
    ports:
      - "8333:8333"
    depends_on:
      - manage
