
# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
#cmd = "go run main.go server"
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main server"
include_ext = ["go", "tpl", "tmpl", "html", "yml"]
exclude_dir = [ "tmp", "vendor", "build", "dist", ".git", ".idea"]
include_dir = []
exclude_file = []
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true