debug: false

secret: "secret"

gorm:
  driver: "postgres"
  dsn: "host=localhost user=postgres password=dora_postgres_password dbname=dora-dev port=5432 sslmode=disable TimeZone=Asia/Shanghai"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0

nsq:
  address:
  topic: ""
  channel: ""

aliyun:
  accesskey: ""
  secret: ""
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  bucket: ""

slsLog:
  accesskey: ""
  secret: ""
  endpoint: "cn-hangzhou.log.aliyuncs.com"
  project: "dora-test"
  logStore: "event-store"
  topic: "browser"

mail:
  host: "smtp.qq.com"
  port: "587"
  username: ""
  password: ""

