version: "3.7"

services:
  # 数据库
  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dora-dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dora_postgres_password
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  # redis
  redis:
    image: redis:latest
    command: redis-server --requirepass dora_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redata:/data

  # sourcemap
  sourcemap:
    image: registry.cn-hangzhou.aliyuncs.com/nancode/dora-parser:latest
    ports:
      - "6667:6667"
    volumes:
      - sourcemapdata:/usr/src/dora-parser

  # 消息队列
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd
    ports:
      - "4171:4171"

volumes:
  pgdata:
  redata:
  sourcemapdata:
